# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rdsb_wrappers", use_symbols = TRUE, package_name = "rdsb")

#' @usage NULL
#' @useDynLib rdsb, .registration = TRUE
NULL

#' Write the compressed data

#' Write object to bundle file in rust
#' @param file_path path to the file
#' @param ser_obj serialized object
#' @param offset the offset of the object in the file
#' @param index_size the size of the index table; -1 if not applicable, only relevant for appending
write_data_object <- function(file_path, ser_obj, offset, index_size) .Call(wrap__write_data_object, file_path, ser_obj, offset, index_size)

#' Read object from bundle file in rust
#' @param file_path path to the file
#' @param offset the offset of the object in the file
#' @param size the size of the object in the file
read_data_object <- function(file_path, offset, size) .Call(wrap__read_data_object, file_path, offset, size)

#' Read object from bundle file in rust directly to a buffer in R
#' @param file_path path to the file
#' @param r_buf the R buffer to read into must be raw(...)
#' @param offset the offset of the object in the file
#' @param size the size of the object in the file
read_data_object_to_R_buffer <- function(file_path, r_buf, offset, size) .Call(wrap__read_data_object_to_R_buffer, file_path, r_buf, offset, size)


# nolint end
